server:
  port: 10001
eureka:
  instance:
    appname: user-service
　client:
　　serviceUrl:
　　　defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service
org:
  dromara:
    hmily :
      serializer : kryo
      recoverDelayTime : 128
      retryMax : 30
      scheduledDelay : 128
      scheduledThreadMax :  10
      repositorySupport : db
      hmilyDbConfig :
        driverClassName  : com.mysql.jdbc.Driver
        url :  jdbc:mysql://localhost:3306/tcc?useUnicode=true&amp;characterEncoding=utf8
        username : root
        password : 1234